export const GET_STUDENTS = "GET_STUDENTS";
export const START_STUDENTS = "START_STUDENTS";
export const SUCCESS_STUDENTS = "SUCCESS_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
