export const studentState = {
  form: {
    name: {
      type: "input",
      format: "text",
      placeholder: "Имя",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 2,
      },
      valid: false,
      touched: false,
    },
    lName: {
      type: "input",
      format: "text",
      placeholder: "Фамилия",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 3,
      },
      valid: false,
      touched: false,
    },
    year: {
      type: "input",
      format: "text",
      placeholder: "Дата рождения",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 1,
      },
      valid: false,
      touched: false,
    },
    age: {
      type: "input",
      format: "text",
      placeholder: "Возраст",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 1,
      },
      valid: false,
      touched: false,
    },
    faculty: {
      type: "input",
      format: "text",
      placeholder: "Факультет",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 3,
      },
      valid: false,
      touched: false,
    },
    dateReceipt: {
      type: "input",
      format: "text",
      placeholder: "Дата поступления",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 1,
      },
      valid: false,
      touched: false,
    },
    course: {
      type: "input",
      format: "text",
      placeholder: "Курс",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 1,
      },
      valid: false,
      touched: false,
    },
    address: {
      type: "textarea",
      format: "text",
      placeholder: "Адрес",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 6,
      },
      valid: false,
      touched: false,
    },
    phone: {
      type: "input",
      format: "text",
      placeholder: "Телефон",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 6,
      },
      valid: false,
      touched: false,
    },
    photo: {
      type: "input",
      format: "text",
      placeholder: "Фото",
      value: "",
      class: "",
      required: true,
      validation: {
        required: true,
        minLength: 6,
      },
      valid: false,
      touched: false,
    },
  },
  formIsValid: false,
  show: false,
};
