export const GET_STUDENTS = "GET_STUDENTS";
export const START_STUDENTS = "START_STUDENTS";
export const SUCCESS_STUDENTS = "SUCCESS_STUDENTS";

export const ADD_STUDENT_START = "ADD_STUDENT_START";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";

export const SORT_STUDENTS = "SORT_STUDENTS";

export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";

export const EDIT_STUDENT_START = "EDIT_STUDENT_START";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";
