export const GET_STUDENTS = "GET_STUDENTS";
export const START_STUDENTS = "START_STUDENTS";
export const SUCCESS_STUDENTS = "SUCCESS_STUDENTS";

export const ADD_STUDENT_START = "ADD_STUDENT_START";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";

export const SORT_STUDENTS = "SORT_STUDENTS";

export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";

export const EDIT_STUDENT_START = "EDIT_STUDENT_START";
export const EDIT_STUDENT_SUCCESS = "EDIT_STUDENT_SUCCESS";
export const EDIT_STUDENT_ERROR = "EDIT_STUDENT_ERROR";

/* USERS */
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const CLEAR_ERROR = "CLEAR_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const AUTH_ERROR = "AUTH_ERROR";
